# Generated by Django 4.2 on 2026-01-20 18:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto (SKU)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.CharField(blank=True, help_text='Categoría del producto', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Si el producto está disponible para la venta')),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen del producto', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='productos_codigo_1fb639_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='productos_categor_9696c3_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='productos_activo_aa3d01_idx'),
        ),
    ]
