# Generated by Django 4.2 on 2026-01-20 18:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la venta')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='COMPLETADA', help_text='Estado actual de la venta', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones o notas adicionales', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente que realizó la compra', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad de unidades vendidas', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal (cantidad × precio_unitario)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(help_text='Producto vendido', on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('venta', models.ForeignKey(help_text='Venta a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'detalle_ventas',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente', 'fecha_venta'], name='ventas_cliente_9f0a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='ventas_estado_505824_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['-fecha_venta'], name='ventas_fecha_v_fe63b7_idx'),
        ),
    ]
